EasyCRM/Controllers/CompanyController.cs
using EasyCRM.BAL.Interface;
using EasyCRM.DAL.Entity.DataModel;
using Microsoft.AspNetCore.Mvc;
using EasyCRM.Models.ViewModels;
using EasyCRM.DAL.Migrations;
using EasyCRM.Models;

namespace EasyCRM.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyservice;
        private readonly ILogger<CompanyController> _logger;
        public CompanyController(ILogger<CompanyController> logger, ICompanyService companyservice)
        {
            _logger = logger;
            _companyservice = companyservice;
        }
        public async Task<IActionResult> Index(string filter_companyName = "")
        {
            _logger.LogInformation("FilterCompany By Name...");
            List<CompanyVM> companies = new List<CompanyVM>();

            if (!string.IsNullOrEmpty(filter_companyName))
            {
                companies = await _companyservice.GetCompanyByName(filter_companyName);
            }
            else
                companies = await _companyservice.GetCompanyName();

            return View(companies);
        }
        [HttpPost]
        public async Task<IActionResult> Index(CompanyFilterVM filter)
        {
            _logger.LogInformation("FilterCompany By Name...");
            List<CompanyVM> companies = new List<CompanyVM>();

            if (!string.IsNullOrEmpty(filter.companyName))
            {
                companies = await _companyservice.GetCompanyByName(filter.companyName);
            }
            else
                companies = await _companyservice.GetCompanyName();

            return View(companies);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> SaveCompany(CompanyVM obj)
        {
            _logger.LogInformation("Save Company....");
            if (obj.CompanyId > 0)
            {
                await _companyservice.UpdateCompany(obj);
            }
            else
            {
                await _companyservice.CreateCompany(obj);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Add()
        {
            _logger.LogInformation("Add Company....");
            return View();

        }
        public async Task<IActionResult> Edit(int id)
        {
            _logger.LogInformation("Edit Company....");
            var company = await _companyservice.GetCompanyById(id);
            return View(company);
        }

        public async Task<IActionResult> Delete(int id)
        {
            _logger.LogInformation("Delete Company....");
            //var company = await _companyservice.GetCompanyById(id);
            await _companyservice.DeleteCompany(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

EasyCRM/Views/Company/Add.cshtml
@Html.Partial("_partialViewCompany", new EasyCRM.Models.ViewModels.CompanyVM())

EasyCRM/Views/Company/Edit.cshtml
@model EasyCRM.Models.ViewModels.CompanyVM;

@{
}

@Html.Partial("_partialViewCompany", Model);

EasyCRM/Views/Company/Index.cshtml
@using EasyCRM.Models.ViewModels;
@model IEnumerable<CompanyVM>;
@{
    ViewData["Title"] = "Comapmy";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        table, th, td {
            border: 2px solid black;
         
        }
    </style>
</head>
<body>
    <div>
        <form asp-action="Index" asp-controller="Company" method="post">
            <div class="form-group">
                <span>Company Name</span>
                <input type="text" id="companyName" name="companyName" />
                </div>
            <input type="submit" value=" filter" />
        </form>
    </div>
<table widht="100%">
    <tr >
        <th>Company Id</th>
        <th>Company Name</th>
        <th>Company Description</th>
        <th>Company Address</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CompanyId</td>
            <td>@item.CompanyName</td>
            <td>@item.CompanyDescription</td>
            <td>@item.CompanyAddress</td>
                <td><a href="@Url.Action("Edit","Company")/@item.CompanyId">Edit</a></td>
                <td><a href="@Url.Action("Delete","Company")/@item.CompanyId">Delete</a></td>
        </tr>

    }
</table>


    <a class="btn btn-primary" href="@Url.Action("Add","Company")">Add</a>
</body>
</html>