EasyCRM/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using EasyCRM.BAL.Service;
using EasyCRM.BAL.Interface;
using EasyCRM.Models.ViewModels;

namespace EasyCRM.Controllers
{
    public class ReportController : Controller
    {
        private readonly IReportService _reportService;
        private readonly ILogger<ReportController> _logger;
        public ReportController(ILogger<ReportController> logger, IReportService reportService) 
        {
            _logger = logger;
            _reportService = reportService;
        }
        public IActionResult Index()
        {
            _logger.LogInformation("Report Page");
            
            return View();
        }

        public async Task<IActionResult> ProductReport(string filter_productReport = "")
        {
            _logger.LogInformation("ProductReport called ");
            List<ProductReportVM> lstobj = new List<ProductReportVM>();
            if(!string.IsNullOrEmpty(filter_productReport)) 
            {
                lstobj = await _reportService.GetProductReport(filter_productReport);
            }
            else
            lstobj = await _reportService.GetProductReport();
            
            return View(lstobj);
        }


        public async Task<IActionResult> QueryReport()
        {
            _logger.LogInformation("QueryReport called ");
            List<ProductReportVM> lstobj = await _reportService.GetQueryReport();
            return View(lstobj);
        }
    }
}

EasyCRM/Views/Report/Index.cshtml
@using EasyCRM.Models.ViewModels;
@model IEnumerable<ProductReportVM>;
@{
    ViewData["Title"] = "CustomerReport";
}
<!DOCTYPE html>
<html>
<head>
    <h1 class="display-4">Repots Page</h1>
    <a class="btn btn-primary" href="@Url.Action("ProductReport","Report")">ProductReport</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a class="btn btn-primary" href="@Url.Action("QueryReport","Report")">QueryReport</a>
    <style>
        table, th, td {
            border: 2px solid black;
        }
    </style>
</head>
@*<body>
    
    <table widht="100%">
        <tr>
            
            <th>ProductName</th>
            <th>CompanyName</th>
            <th>CustomerName</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>@item.productName</td>
                <td>@item.companyName</td>
                <td>@item.customerName</td>
                
            </tr>

        }
    </table>


    
</body>*@
</html>

EasyCRM/Views/Report/ProductReport.cshtml
@using EasyCRM.Models.ViewModels;
@model IEnumerable<ProductReportVM>;
@{
    ViewData["Title"] = "CustomerReport";
}
<!DOCTYPE html>
<html>
<head>

   
    <style>
        table, th, td {
            border: 2px solid black;
        }
    </style>
</head>
<body>

    <table widht="100%">
        <tr>

            <th>ProductName</th>
            <th>CompanyName</th>
            <th>CustomerName</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.productName</td>
                <td>@item.companyName</td>
                <td>@item.customerName</td>

            </tr>

        }
    </table>



</body>
</html>

EasyCRM/Views/Report/QueryReport.cshtml
@using EasyCRM.Models.ViewModels;
@model IEnumerable<ProductReportVM>;
@{
    ViewData["Title"] = "CustomerReport";
}
<!DOCTYPE html>
<html>
<head>
    <style>
        table, th, td {
            border: 2px solid black;
        }
    </style>
</head>
<body>

    <table widht="100%">
        <tr>

            <th>CompanyName</th>
            <th>CustomerName</th>
            <th>ProductName</th>
            <th>QueryDescription</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>

                <td>@item.companyName</td>
                <td>@item.customerName</td>
                <td>@item.productName</td>
                <td>@item.QueryDescription</td>

            </tr>

        }
    </table>



</body>
</html>